# Generated by Django 4.1.4 on 2022-12-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="offer", name="BorrowerID",),
        migrations.AddField(
            model_name="loan", name="BorrowerID", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="investor", name="balance", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="loan", name="amount", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="loan", name="period", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="offer", name="AIR", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="offer", name="InvestorID", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="offer", name="LoanID", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="payments", name="LoanID", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="payments", name="amount", field=models.IntegerField(),
        ),
    ]
