# Generated by Django 4.1.4 on 2022-12-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_remove_offer_borrowerid_loan_borrowerid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="date",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
